name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ["buster", "stretch", "jessie"]

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: texlive
        file: ./Dockerfile
        push: true
        build-args: |
          RELEASE=${{ matrix.release }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/texlive:${{ matrix.release }}
    - name: Set latest
      if: ${{ matrix.release }} == "buster"
      run: |
        docker tag ${{ steps.docker_build.outputs.digest }} ${{ secrets.DOCKER_HUB_USERNAME }}/texlive:latest &&
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/texlive:latest
